version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: plantillagen-db
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: plantillagen
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18/docker
      - ./src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    restart: unless-stopped

volumes:
  pgdata:
